[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
unreachable = "1.0.0"
num = "0.4.1"
winnow = "0.5.19"
itertools = "0.12.0"
colored = "2.1.0"
memoize = "0.4.1"
list_files_macro = "0.1.0"
regex = "1.10.2"
rand = "0.8.5"
rayon = "1.8.1"